name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution, and replace "e2e" with "e2e-ci" in the command below
      # - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - - run: npm ci --legacy-peer-deps  # Use --legacy-peer-deps to avoid peer dependency conflicts in CI. Your package.json specifies vitest@4.0.9 (dev dependency)
                                          # @angular/build@20.3.27 expects vitest@^3.1.1, which causes npm ci to fail. Using --legacy-peer-deps allows npm to ignore peer dependency conflicts and install the
                                          # dependencies successfully.
    # - run: npm ci # Use this line instead if you want npm ci to fail on peer dependency conflicts
      - run: npx playwright install --only-shell

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      - run: npx nx run-many -t lint test build typecheck e2e
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: npx nx fix-ci
        if: always()
